import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  searchResult,
}: Readonly<{
  children: React.ReactNode;
  searchResult: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[100vw] h-full py-5">
          <Navbar />
        </div>
        <div className="w-[100vw] h-full py-5">
          {children}
          <div className="w-[90%] md:w-[60%]  mx-auto py-3">{searchResult}</div>
        </div>
      </body>
    </html>
  );
}
